//task 23
var car = "subaru";
//console.log("is car == `subaru`? predict true ");
//console.log(car == "subaru");
//console.log("is car != 'toyota corrola'? predict true");
//console.log(car != 'toyota corrola');
//console.log("is car == 'subaru'? predict false ");
//console.log(car == 'subaru');
//console.log("is car == 'SUBARU'? predict false");
//console.log(car =='SUBARU');
//console.log("is car. length == 6? predict true");
//console.log(car.length == 6);
//console.log("is car. length != 10? predict true");
//console.log(car.length != 10);
//console.log("is 10 >4 5 ? predict false");
//console.log(10 > 45);
//console.log("is 3 <= 2 ? predict false");
//console.log(3 <= 2);
//console.log("is 72 >= 83 ? predict false");
//console.log(72 >= 83);
console.log("is car == 'subaru' && car.length ==6? predict true");
console.log(car == 'subaru' && car.length == 6);
